### Корректный тест
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "1212121212",
  "regionNumber": 12,
  "capital": "123456789.12"
}

### Некорректный ИНН 1
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "123",
  "regionNumber": 123,
  "capital": "123456789.12"
}

### Некорректный ИНН 2
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "123123123123123",
  "regionNumber": 123,
  "capital": "123456789.12"
}

### Некорректный капитал
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "1212121212",
  "regionNumber": 12,
  "capital": "0.00"
}

### ИП
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "123123123123",
  "regionNumber": 123,
  "capital": "123456789.12"
}

### Нерезидент РФ
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "9909090909",
  "regionNumber": 123,
  "capital": "123456789.12"
}

### Красноярский край
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "1212121212",
  "regionNumber": 24,
  "capital": "123456789.12"
}

### Капитал ровно 5 миллионов
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "1212121212",
  "regionNumber": 123,
  "capital": "5000000.00"
}

### Капитал меньше 5 миллионов
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "inn": "1212121212",
  "regionNumber": 123,
  "capital": "4500000.00"
}
